LOAD DATA INFILE 'Employee.csv' 
INTO TABLE Employee 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'Employee_time.csv' 
INTO TABLE Employee_time 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'System_time_in_month.csv' 
INTO TABLE System_Time_In_Month
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'Create_E_Naryad_Table_1.csv' 
INTO TABLE Create_E_Naryad_Table_1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'Create_E_Naryad_Table_2.csv' 
INTO TABLE Create_E_Naryad_Table_2
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'Messages.csv' 
INTO TABLE Messages
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;



LOAD DATA INFILE 'Disposal_jounal.csv' 
INTO TABLE Disposal_jounal
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'Create_E_Naryad_Table_3.csv' 
INTO TABLE Create_E_Naryad_Table_3
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'Create_E_Naryad_Table_4.csv' 
INTO TABLE Create_E_Naryad_Table_4
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


