# Generated by Django 3.1.7 on 2021-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_h_at_work', models.BigIntegerField(null=True)),
                ('holiday_h', models.BigIntegerField(null=True)),
                ('sick_h', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
