# Generated by Django 3.1.7 on 2021-04-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0003_auto_20210416_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entrusted',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manufacturer_work_manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='name',
        ),
        migrations.RemoveField(
            model_name='to_observer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='work_manager',
            name='name',
        ),
        migrations.AddField(
            model_name='admitting',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
        migrations.AddField(
            model_name='entrusted',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
        migrations.AddField(
            model_name='manufacturer_work_manager',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
        migrations.AddField(
            model_name='team_members',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
        migrations.AddField(
            model_name='to_observer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
        migrations.AddField(
            model_name='work_manager',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee'),
        ),
    ]
