# Generated by Django 3.1.7 on 2021-04-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0004_auto_20210416_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('technical_activities', models.CharField(max_length=200, null=True)),
                ('place_name_work', models.CharField(max_length=200, null=True)),
                ('started_work', models.DateField()),
                ('work_done', models.DateField()),
                ('person_give_naryad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee')),
                ('team_members', models.ManyToManyField(to='a_page.Team_members')),
                ('work_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.work_supervisor')),
            ],
        ),
    ]
