# Generated by Django 3.1.7 on 2021-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0007_employee_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text1',
            new_name='disconnected_where',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='username',
            new_name='enar_give',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text2',
            new_name='name_electrical',
        ),
        migrations.RenameField(
            model_name='create_e_naryad_table_1',
            old_name='workplace_preparation_text3',
            new_name='separate_instructions',
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_1',
            name='single_line_diagram',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
