# Generated by Django 3.1.7 on 2021-05-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0008_auto_20210512_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='сreate_e_naryad_table_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('employee_preparedness_time', models.DateField()),
                ('finish_work', models.DateField()),
                ('name_electrical', models.TextField()),
                ('separate_instructions', models.TextField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('single_line_diagram', models.ImageField(blank=True, null=True, upload_to='')),
                ('start_work', models.DateField()),
                ('disconnected_where', models.TextField()),
                ('admitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.admitting')),
                ('an_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.an_object')),
                ('category_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.category_of_work')),
                ('enar_give', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee')),
                ('entrusted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.entrusted')),
                ('manufacturer_work_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.manufacturer_work_manager')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.organization')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.plot')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.subdivision')),
                ('team_members', models.ManyToManyField(to='a_page.Team_members')),
                ('to_observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.to_observer')),
                ('work_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.work_manager')),
            ],
        ),
        migrations.DeleteModel(
            name='create_e_naryad_table_1',
        ),
    ]
