# Generated by Django 3.1.7 on 2021-05-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0009_auto_20210512_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='To_observer',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='An_object',
            new_name='Object',
        ),
        migrations.RenameModel(
            old_name='Manufacturer_work_manager',
            new_name='Observer',
        ),
        migrations.RenameField(
            model_name='сreate_e_naryad_table_1',
            old_name='employee_preparedness_time',
            new_name='emergency_preparedness_time',
        ),
        migrations.RenameField(
            model_name='сreate_e_naryad_table_1',
            old_name='to_observer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='сreate_e_naryad_table_1',
            old_name='an_object',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='сreate_e_naryad_table_1',
            old_name='manufacturer_work_manager',
            new_name='observer',
        ),
    ]
