# Generated by Django 3.1.7 on 2021-05-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0010_auto_20210512_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='сreate_e_naryad_table_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('signature_enar_give', models.ImageField(blank=True, null=True, upload_to='')),
                ('responsible_manager', models.CharField(max_length=200, null=True)),
                ('signature_responsible_manager', models.ImageField(blank=True, null=True, upload_to='')),
                ('enar_give', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee')),
            ],
        ),
    ]
