# Generated by Django 3.1.7 on 2021-05-13 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0011_сreate_e_naryad_table_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_e_naryad_table_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('reported', models.CharField(max_length=200, null=True)),
                ('responsible_manager', models.CharField(max_length=200, null=True)),
                ('signature_manufacturer', models.ImageField(blank=True, null=True, upload_to='')),
                ('signature_responsible_manager', models.ImageField(blank=True, null=True, upload_to='')),
                ('signature_admitting', models.ImageField(blank=True, null=True, upload_to='')),
                ('admitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.admitting')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='create_e_naryad_table_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_naryad', models.IntegerField()),
                ('signature_enar_give', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_time', models.DateField()),
                ('workplaces_prepared', models.TextField()),
                ('agreed', models.CharField(max_length=200, null=True)),
                ('responsible_manager', models.CharField(max_length=200, null=True)),
                ('admitting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.admitting')),
                ('enar_give', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.employee')),
            ],
        ),
    ]
