# Generated by Django 3.1.7 on 2021-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0013_auto_20210513_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='сreate_e_naryad_table_1',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
