# Generated by Django 3.1.7 on 2021-05-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0015_auto_20210513_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_e_naryad_table_3',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.organization'),
        ),
        migrations.AddField(
            model_name='create_e_naryad_table_4',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.organization'),
        ),
        migrations.AddField(
            model_name='сreate_e_naryad_table_2',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='a.jpg', null=True, upload_to=''),
        ),
    ]
