# Generated by Django 3.1.7 on 2021-05-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0016_auto_20210513_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_e_naryad_table_3',
            name='responsible_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.work_manager'),
        ),
        migrations.AlterField(
            model_name='create_e_naryad_table_4',
            name='responsible_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.work_manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='сreate_e_naryad_table_2',
            name='responsible_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_page.work_manager'),
        ),
    ]
