# Generated by Django 3.1.7 on 2021-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0017_auto_20210514_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_e_naryad_table_3',
            name='responsible_manager',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='create_e_naryad_table_4',
            name='responsible_manager',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='сreate_e_naryad_table_2',
            name='responsible_manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
